-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/IOd1Fp9xR1Eh62l
6oBKIzvjGygQvS8QrSQbFYxF1j6gCgYIKoZIzj0DAQehRANCAAR5Zn95ftqsTrgO
vvE+/48GgBbaoXzQcxUAKGb/dVDiSp+nvAk0WyzNaXzCikr/LZbwveraHxo7lpmd
rBjGdzy5
-----END PRIVATE KEY-----